services:
  postgres:
    container_name: "imagehosting-db"
    image: postgres:17-alpine
    ports:
    - 7990:5432
    env_file:
      - example.env
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    
  backend:
    container_name: "imagehosting-backend"
    build: 
      context: backend
      dockerfile: ./docker/Dockerfile
    env_file:
      - example.env
    ports:
      - "8899:8899"
    volumes:
      - ./images:/var/webapp/imagehosting/images
 

volumes:
  db-data:
    driver: local