x-env-file: &ENV_FILE example.env

x-defaults: &defaults
  restart: unless-stopped
  networks:
    - net-imgh
  env_file:
    - *ENV_FILE

x-frontend-build-args: &frontend-build-args
  - VITE_FRONTEND_BACKEND_CONNECTION_STRING=${VITE_FRONTEND_BACKEND_CONNECTION_STRING}

services:
  postgres:
    container_name: "imagehosting-db"
    image: postgres:17-alpine
    <<: *defaults
    ports:
      - "127.0.0.1:7990:${POSTGRES_PORT}/tcp"
    restart: on-failure
    volumes:
      - vol-imgh-db-data:/var/lib/postgresql/data

  minio:
    image: "imagehosting-minio"
    build:
      context: .
      dockerfile: ./s3/docker/minio.Dockerfile
    container_name: "imagehosting-minio"
    <<: *defaults
    volumes:
      - vol-imgh-minio-data:/data
    ports:
      - "127.0.0.1:9000:9000/tcp"
      - "127.0.0.1:9001:9001/tcp"
    depends_on:
      - postgres

  minio-config:
    image: "imagehosting-minio-config"
    build:
      context: .
      dockerfile: ./s3/docker/minio-config.Dockerfile
    container_name: "imagehosting-minio-config-dev"
    <<: *defaults
    restart: on-failure
    depends_on:
      - minio

  backend:
    container_name: "imagehosting-backend"
    build: 
      context: backend
      dockerfile: ./docker/Dockerfile
    <<: *defaults
    ports:
      - "${BACKEND_OPEN_CONNECTION_STRING}"
      - "${BACKEND_DEBUG_CONNECTION_STRING}"
    volumes:
      - ./images:/var/webapp/imagehosting/images
    depends_on:
      - postgres
      - minio

  frontend:
    container_name: "imagehosting-frontend"
    build: 
      context: frontend
      dockerfile: ./docker/Dockerfile
      args: *frontend-build-args
    <<: *defaults
    depends_on:
      - backend

  proxy:
    container_name: "imagehosting-proxy"
    build: 
      context: proxy
      dockerfile: ./docker/Dockerfile
    <<: *defaults
    ports:
      - "${PROXY_OPEN_CONNECTION_STRING}"
      - "${PROXY_OLD_OPEN_CONNECTION_STRING}"
    depends_on:
      - backend
      - frontend

volumes:
  vol-imgh-db-data:
    driver: local
  vol-imgh-minio-data:
    driver: local

networks:
  net-imgh: