server.port=8899

spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:7990/database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.mvc.hiddenmethod.filter.enabled=true