# Server
server.port=8899
# logging.level.root=DEBUG

# Servlet
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=200MB

# SQL
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.mode=always

# Database connection
spring.datasource.url=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Database
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.mvc.hiddenmethod.filter.enabled=true

# S3 storage
cloud.aws.region.static=us-east-1
cloud.aws.credentials.endpoint=http://minio:9000
cloud.aws.credentials.access-key=${MINIO_ROOT_USER}
cloud.aws.credentials.secret-key=${MINIO_ROOT_PASSWORD}
cloud.aws.s3.bucket.name=${MINIO_STORAGE_BUCKET_NAME}
cloud.aws.s3.path-style.enabled=true

# Application
app.image-service=img-service-s3
